# -*- coding: utf-8 -*-
import os
from pathlib import Path

def w(path, lines):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("  [ok] " + path)

# ============ CONTRIBUTING.md ============
c = []
c.append("# Contributing to CleanIP")
c.append("")
c.append("Thanks for considering a contribution! \U0001F389")
c.append("")
c.append("## Quick Start")
c.append("")
c.append("```bash")
c.append("git clone https://github.com/khademdev/cleanip.git")
c.append("cd cleanip")
c.append("make build")
c.append("```")
c.append("")
c.append("## Ways to Contribute")
c.append("")
c.append("- \U0001F41B **Report bugs** \u2014 open an issue")
c.append("- \U0001F4A1 **Suggest features** \u2014 use the feature template")
c.append("- \U0001F4DD **Improve docs** \u2014 fix typos, clarify wording")
c.append("- \U0001F30D **Translate** \u2014 add a language to the UI")
c.append("- \U0001F9EA **Test** \u2014 try new presets, report edge cases")
c.append("- \U0001F4BB **Code** \u2014 submit a pull request")
c.append("")
c.append("## Pull Request Workflow")
c.append("")
c.append("1. **Fork** the repository")
c.append("2. **Create a branch**: `git checkout -b feat/your-feature`")
c.append("3. **Make your changes**")
c.append("4. **Verify locally**:")
c.append("   ```bash")
c.append("   gofmt -l .")
c.append("   go vet ./...")
c.append("   go build -trimpath -ldflags=\"-s -w\" -o /tmp/cleanip .")
c.append("   ```")
c.append("5. **Test the UI** in both languages (fa / en) and on mobile (700px / 480px / 360px)")
c.append("6. **Open a PR** with a clear description")
c.append("")
c.append("## Code Style")
c.append("")
c.append("### Go")
c.append("- `gofmt` defaults")
c.append("- Prefer standard library over third-party packages")
c.append("- Keep functions small and focused")
c.append("- Handle errors explicitly")
c.append("")
c.append("### HTML / CSS / JavaScript")
c.append("- Everything self-contained (no external CDNs except Vazirmatn)")
c.append("- Every user-facing string needs a key in **both** `I18N.fa` and `I18N.en`")
c.append("- Keep the mobile layout working")
c.append("")
c.append("## Commit Messages")
c.append("")
c.append("Follow [Conventional Commits](https://www.conventionalcommits.org/):")
c.append("")
c.append("```")
c.append("feat: add Shadowsocks 2022 support")
c.append("fix: prevent panic on empty config")
c.append("docs: clarify ECH setup in README")
c.append("style: gofmt all files")
c.append("refactor: extract SNI resolver")
c.append("test: add parseURI table tests")
c.append("chore: bump Go version to 1.22")
c.append("```")
c.append("")
c.append("## Good First Issues")
c.append("")
c.append("Look for issues labeled [`good first issue`](../../labels/good%20first%20issue) \u2014 these are beginner-friendly and a great place to start.")
c.append("")
c.append("## Need Help?")
c.append("")
c.append("Open an issue with the `question` label, or reach out to the maintainer.")
c.append("")
c.append("---")
c.append("")
c.append("**Maintainer:** Meysam Khademshams ([@khademdev](https://github.com/khademdev))")
w("CONTRIBUTING.md", c)

# ============ CODE_OF_CONDUCT.md ============
c = []
c.append("# Contributor Covenant Code of Conduct")
c.append("")
c.append("## Our Pledge")
c.append("")
c.append("We as members, contributors, and leaders pledge to make participation")
c.append("in our community a harassment-free experience for everyone, regardless")
c.append("of age, body size, visible or invisible disability, ethnicity, sex")
c.append("characteristics, gender identity and expression, level of experience,")
c.append("education, socio-economic status, nationality, personal appearance,")
c.append("race, religion, or sexual identity and orientation.")
c.append("")
c.append("## Our Standards")
c.append("")
c.append("Examples of behavior that contributes to a positive environment:")
c.append("")
c.append("- Demonstrating empathy and kindness toward other people")
c.append("- Being respectful of differing opinions, viewpoints, and experiences")
c.append("- Giving and gracefully accepting constructive feedback")
c.append("- Accepting responsibility and apologizing to those affected by our mistakes")
c.append("- Focusing on what is best for the overall community")
c.append("")
c.append("Examples of unacceptable behavior:")
c.append("")
c.append("- The use of sexualized language or imagery")
c.append("- Trolling, insulting or derogatory comments, personal or political attacks")
c.append("- Public or private harassment")
c.append("- Publishing others' private information without explicit permission")
c.append("- Other conduct which could reasonably be considered inappropriate")
c.append("")
c.append("## Enforcement")
c.append("")
c.append("Instances of abusive, harassing, or otherwise unacceptable behavior may be")
c.append("reported to the community leaders responsible for enforcement via GitHub's")
c.append("[private report](../../security/advisories/new) feature.")
c.append("")
c.append("All complaints will be reviewed and investigated promptly and fairly.")
c.append("")
c.append("## Attribution")
c.append("")
c.append("This Code of Conduct is adapted from the [Contributor Covenant](https://www.contributor-covenant.org),")
c.append("version 2.1, available at")
c.append("[https://www.contributor-covenant.org/version/2/1/code_of_conduct.html](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html).")
w("CODE_OF_CONDUCT.md", c)

# ============ SECURITY.md ============
c = []
c.append("# Security Policy")
c.append("")
c.append("## Supported Versions")
c.append("")
c.append("| Version | Supported |")
c.append("|---------|-----------|")
c.append("| 1.0.x   | \u2705 |")
c.append("")
c.append("## Reporting a Vulnerability")
c.append("")
c.append("**Please do NOT open a public issue for security problems.**")
c.append("")
c.append("Instead, report privately via GitHub's")
c.append("[Security Advisory](../../security/advisories/new) feature.")
c.append("")
c.append("Include:")
c.append("")
c.append("- Description of the vulnerability")
c.append("- Steps to reproduce")
c.append("- Potential impact")
c.append("- Any suggested mitigation")
c.append("")
c.append("You will receive a response within **72 hours**.")
c.append("")
c.append("## Scope")
c.append("")
c.append("CleanIP runs on `127.0.0.1` only and makes no outbound calls except to")
c.append("Cloudflare's public APIs. We still appreciate reports on:")
c.append("")
c.append("- Local privilege escalation")
c.append("- Arbitrary file read/write")
c.append("- Command injection via config strings")
c.append("- XSS in the web UI")
c.append("- Denial of service via crafted configs")
c.append("")
c.append("## Out of Scope")
c.append("")
c.append("- Vulnerabilities in third-party components (Xray, Go runtime)")
c.append("- Issues requiring an already-compromised local machine")
c.append("- Social engineering")
c.append("")
c.append("## Preferred Languages")
c.append("")
c.append("English, Persian (\u0641\u0627\u0631\u0633\u06CC)")
c.append("")
c.append("---")
c.append("")
c.append("**Maintainer:** Meysam Khademshams ([@khademdev](https://github.com/khademdev))")
w("SECURITY.md", c)

# ============ Bug report template ============
c = []
c.append("name: \U0001F41B Bug report")
c.append("description: Report a bug or unexpected behavior")
c.append("title: \"[Bug] \"")
c.append("labels: [\"bug\", \"needs-triage\"]")
c.append("body:")
c.append("  - type: markdown")
c.append("    attributes:")
c.append("      value: |")
c.append("        Thanks for taking the time to report a bug! \U0001F64F")
c.append("")
c.append("  - type: textarea")
c.append("    id: description")
c.append("    attributes:")
c.append("      label: Description")
c.append("      description: A clear and concise description of the bug")
c.append("    validations:")
c.append("      required: true")
c.append("")
c.append("  - type: textarea")
c.append("    id: steps")
c.append("    attributes:")
c.append("      label: Steps to reproduce")
c.append("      placeholder: |")
c.append("        1. Open cleanip.exe")
c.append("        2. Set preset to Deep")
c.append("        3. Click Start Scan")
c.append("        4. See error")
c.append("    validations:")
c.append("      required: true")
c.append("")
c.append("  - type: textarea")
c.append("    id: expected")
c.append("    attributes:")
c.append("      label: Expected behavior")
c.append("    validations:")
c.append("      required: true")
c.append("")
c.append("  - type: input")
c.append("    id: os")
c.append("    attributes:")
c.append("      label: Operating System")
c.append("      placeholder: e.g. Windows 11, Ubuntu 22.04, macOS 14")
c.append("    validations:")
c.append("      required: true")
c.append("")
c.append("  - type: dropdown")
c.append("    id: xray")
c.append("    attributes:")
c.append("      label: Is Xray present?")
c.append("      options:")
c.append("        - \"Yes (xray_core/xray.exe)\"")
c.append("        - \"Yes (in PATH)\"")
c.append("        - \"No\"")
c.append("    validations:")
c.append("      required: true")
c.append("")
c.append("  - type: textarea")
c.append("    id: logs")
c.append("    attributes:")
c.append("      label: Screenshots / Logs")
c.append("      description: Drag and drop images or paste relevant output")
c.append("    validations:")
c.append("      required: false")
w(".github/ISSUE_TEMPLATE/bug.yml", c)

# ============ Feature template ============
c = []
c.append("name: \U0001F4A1 Feature request")
c.append("description: Suggest an idea for CleanIP")
c.append("title: \"[Feature] \"")
c.append("labels: [\"enhancement\", \"needs-triage\"]")
c.append("body:")
c.append("  - type: textarea")
c.append("    id: problem")
c.append("    attributes:")
c.append("      label: Is your feature request related to a problem?")
c.append("      placeholder: I'm always frustrated when...")
c.append("    validations:")
c.append("      required: true")
c.append("")
c.append("  - type: textarea")
c.append("    id: solution")
c.append("    attributes:")
c.append("      label: Proposed solution")
c.append("      placeholder: Describe what you'd like to happen")
c.append("    validations:")
c.append("      required: true")
c.append("")
c.append("  - type: textarea")
c.append("    id: alternatives")
c.append("    attributes:")
c.append("      label: Alternatives considered")
c.append("    validations:")
c.append("      required: false")
c.append("")
c.append("  - type: textarea")
c.append("    id: context")
c.append("    attributes:")
c.append("      label: Additional context")
c.append("      placeholder: Screenshots, mockups, links")
c.append("    validations:")
c.append("      required: false")
w(".github/ISSUE_TEMPLATE/feature.yml", c)

# ============ Pull Request template ============
c = []
c.append("<!--")
c.append("  Thanks for opening a pull request!")
c.append("  Please fill in the sections below.")
c.append("-->")
c.append("")
c.append("## \U0001F4DD Description")
c.append("")
c.append("<!-- A clear and concise description of what this PR does. -->")
c.append("")
c.append("## \U0001F517 Related issue")
c.append("")
c.append("<!-- e.g. Closes #42 -->")
c.append("")
c.append("## \U0001F9EA Type of change")
c.append("")
c.append("- [ ] \U0001F41B Bug fix (non-breaking change)")
c.append("- [ ] \u2728 New feature (non-breaking change)")
c.append("- [ ] \U0001F4A5 Breaking change")
c.append("- [ ] \U0001F4DD Documentation update")
c.append("- [ ] \U0001F3A8 UI/UX improvement")
c.append("- [ ] \u267B\uFE0F Refactor")
c.append("- [ ] \u26A1 Performance improvement")
c.append("")
c.append("## \u2705 Checklist")
c.append("")
c.append("- [ ] I have read [CONTRIBUTING.md](../CONTRIBUTING.md)")
c.append("- [ ] `gofmt -l .` returns nothing")
c.append("- [ ] `go vet ./...` passes")
c.append("- [ ] `go build .` succeeds")
c.append("- [ ] I tested both languages (fa / en) if UI changed")
c.append("- [ ] I tested mobile breakpoints (700px, 480px, 360px) if UI changed")
c.append("- [ ] Every new string has keys in **both** `I18N.fa` and `I18N.en`")
c.append("- [ ] No new external dependencies (unless discussed first)")
c.append("")
c.append("## \U0001F4F8 Screenshots")
c.append("")
c.append("<!-- If UI changed, add before/after screenshots. -->")
c.append("")
c.append("## \U0001F4CB Additional notes")
c.append("")
c.append("<!-- Anything else the maintainer should know. -->")
w(".github/PULL_REQUEST_TEMPLATE.md", c)

print("")
print("=" * 50)
print("ALL FILES CREATED SUCCESSFULLY")
print("=" * 50)
print("")
print("Next steps:")
print("  1. git add .")
print("  2. git commit -m 'docs: add contribution guidelines'")
print("  3. git push")
print("  4. Create some 'good first issue' labels on GitHub")